# Subtítulos
sub-auto=fuzzy
sub-font-size=36
sub-bold=yes

sub-color="#FFD700"
sub-border-color="#000000"
sub-border-size=2
sub-shadow-color="#000000"
sub-shadow-offset=1


# Interfaz
save-position-on-quit=yes
# si termina el video entonces empieza desde el principio la proxima vez
resume-playback-check-mtime=yes
watch-later-options=start

osc=yes

# Idiomas
alang=spa,es,es-ES,lat,eng,en
slang=spa,es,es-ES,lat,eng,en


# mantener abierta ventana
# keep-open=yes → mantiene mpv abierto al terminar la reproducción normalmente.
# keep-open=always → también lo mantiene abierto en situaciones donde se cambia entre archivos/playlist.
keep-open=always


